---
  extends:
    - "plugin:@wordpress/eslint-plugin/recommended"
  parserOptions:
    sourceType: module
  env:
    browser: true
    es6: true
    jquery: true
  rules:
    space-in-parens: 0
    wrap-iife: 0
