# Travis CI (MIT License) configuration file
# @link https://travis-ci.org/

# Use new container based environment
sudo: false

# Declare project language.
# @link http://about.travis-ci.org/docs/user/languages/php/
language: php

# Declare versions of PHP to use. Use one decimal max.
# @link http://docs.travis-ci.com/user/build-configuration/
matrix:
    fast_finish: true

    include:
        - php: '5.6'
          env: SNIFF=1
        - php: '7.0'
        - php: '7.1'
        - php: '7.2'
        - php: 'nightly'

    allow_failures:
        - php: nightly

before_install:
  # Install PHP CodeSniffer.
  - if [[ "$SNIFF" == "1" ]]; then composer self-update; fi
  - if [[ "$SNIFF" == "1" ]]; then composer require squizlabs/php_codesniffer; fi
  - if [[ "$SNIFF" == "1" ]]; then composer install; fi
  - if [[ "$SNIFF" == "1" ]]; then npm install; fi
  - phpenv rehash

script:
  # Search for PHP syntax errors.
  - find -L . -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
  # Run i18n.
  - if [[ "$SNIFF" == "1" ]]; then npm run i18n; fi
  # Run lints.
  - if [[ "$SNIFF" == "1" ]]; then npm run lint; fi
  # Run build.
  - if [[ "$SNIFF" == "1" ]]; then npm run build; fi
